draft of task without star
avlin87/epam-learn pull request #13
Opened 2021-04-20 22:26 UTC by avlin87

"Если несоответсвие типов, то дефолтным значением"
т.е. в @Value у нас поле - String value() default "text";
а @Value повесили на поле с integer.

такая ли ситуация имеется в виду?

2021-04-22 06:03 UTC, tlt-java-courses requested changes

2021-04-22 06:03 UTC, tlt-java-courses commented on src/main/java/com/liadov/cat/lesson9/annotations/Entity.java
> + * Entity
JavaDoc. Написать для чего нужна.

2021-04-22 06:03 UTC, tlt-java-courses commented on src/main/java/com/liadov/cat/lesson9/annotations/Value.java
> + * Value
JavaDoc. Написать для чего нужна.

2021-04-22 06:03 UTC, tlt-java-courses commented on src/main/java/com/liadov/cat/lesson9/annotations/Value.java
> +    int intValue() default 0;
А если я повешу аннотацию на boolean значение или на double? Будешь добавлять новые поля сюда? На сколько это корректно?

2021-04-22 06:03 UTC, tlt-java-courses commented on src/main/java/com/liadov/cat/lesson9/pojo/Bridge.java
> +    private static final Logger log = LoggerFactory.getLogger(Book.class);
Опечатка в переданном классе

2021-04-22 06:03 UTC, tlt-java-courses commented on src/main/java/com/liadov/cat/lesson9/pojo/Dog.java
> + * Dog
JavaDoc. В других entity всё ок.

2021-04-22 06:03 UTC, tlt-java-courses commented on src/main/java/com/liadov/cat/lesson9/pojo/Dog.java
> +    @Value(fileName = "src/main/resources/sourceFile.txt")
В задании сказано: `чтобы она дополнительно принимала путь до значения из txt файла` 
Т.е. путь НЕ до файла, а до значения в нём. У тебя переменная может называться в POJO как _age_, а в файле _someExampleAge_, и его мы должны подцепить.

2021-04-22 06:03 UTC, tlt-java-courses commented on src/main/resources/logback.xml
> +    <logger name="com.liadov.cat.Main" level="trace" additivity="false">
Зачем так много указаний одинаковых логгеров? Сделай один для рута проекта.

2021-04-22 06:03 UTC, tlt-java-courses commented on src/main/java/com/liadov/cat/lesson9/FileOperations.java
> +            log.error("error", e);
Давай в начало каждого лога добавлять метод в котором лог вызывается, например 
`log.error("getValueFromFile() - error", e);`

2021-04-22 06:03 UTC, tlt-java-courses commented on src/main/java/com/liadov/cat/Main.java
> +        log.info("\n\nvalues are populated:\n \n{} - from file\n{} - from annotations\n{} - no annotations\n{} - NoValueAnnotationException \n{} - IllegalStateException", dog, human, address, book, b
Длина этой строки > 150 символов

2021-04-22 06:03 UTC, tlt-java-courses commented on src/main/java/com/liadov/cat/lesson9/ReflectionHandler.java
> +    private Object tryToParseInt(Object valueAnnotation) {
К вопросу про добавление новых типов. Придётся ещё и код поддерживать, что не есть лучшее решение

2021-04-22 10:31 UTC, avlin87 commented on src/main/java/com/liadov/cat/lesson9/annotations/Entity.java
> + * Entity
исправил
"Entity annotation for identification of POJO classes"

2021-04-22 10:31 UTC, avlin87 commented on src/main/java/com/liadov/cat/lesson9/annotations/Value.java
> + * Value
исправил
"Value annotation for setting value for Filed/Method for POJO classes
marked by @Entity annotation"

2021-04-22 10:32 UTC, avlin87 commented on src/main/java/com/liadov/cat/lesson9/pojo/Bridge.java
> +    private static final Logger log = LoggerFactory.getLogger(Book.class);
Исправил

2021-04-22 10:35 UTC, avlin87 commented on src/main/java/com/liadov/cat/lesson9/pojo/Dog.java
> + * Dog
Исправил
"Dog - pojo class for test.
Class has @Entity and @Value annotations.
Value annotation setting values from external file."

2021-04-22 10:56 UTC, avlin87 commented on src/main/resources/logback.xml
> +    <logger name="com.liadov.cat.Main" level="trace" additivity="false">
сделал один логер для проекта.

2021-04-22 11:11 UTC, avlin87 commented on src/main/java/com/liadov/cat/lesson9/FileOperations.java
> +            log.error("error", e);
Исправил,
метод был в треугольных скобочках<>
поправил logger **Pattern** чтобы лог был более читаемым.
Пример обновленного лога:
15:10:42.501 [main] TRACE com.liadov.cat.Main: reflectionExample() - from file: Dog{age=20, name=2name}

2021-04-22 11:15 UTC, avlin87 commented on src/main/java/com/liadov/cat/Main.java
> +        log.info("\n\nvalues are populated:\n \n{} - from file\n{} - from annotations\n{} - no annotations\n{} - NoValueAnnotationException \n{} - IllegalStateException", dog, human, address, book, b
разбил на отдельные записи по примерам.

2021-04-22 20:31 UTC, avlin87 commented on src/main/java/com/liadov/cat/lesson9/annotations/Value.java
> +    int intValue() default 0;
удалил int intValue() default 0;

2021-04-22 20:31 UTC, avlin87 commented on src/main/java/com/liadov/cat/lesson9/ReflectionHandler.java
> +    private Object tryToParseInt(Object valueAnnotation) {
добавил класс для конвертации ValueConverter

2021-04-22 21:21 UTC, avlin87 commented on src/main/java/com/liadov/cat/lesson9/pojo/Dog.java
> +    @Value(fileName = "src/main/resources/sourceFile.txt")
исправил

2021-04-24 06:21 UTC, tlt-java-courses requested changes

2021-04-24 06:21 UTC, tlt-java-courses commented on src/test/java/com/liadov/cat/lesson9/FileOperationsTest.java
> + * FileOperationsTest
`Test for {@link FileOperations}`
Текущий javaDoc не информативен

2021-04-24 06:21 UTC, tlt-java-courses commented on src/test/java/com/liadov/cat/lesson9/ReflectionHandlerTest.java
> + * ReflectionHandlerTest
Аналогично

2021-04-24 06:21 UTC, tlt-java-courses commented on src/test/java/com/liadov/cat/lesson9/ValueConverterTest.java
> + * ValueConverterTest
Аналогично

2021-04-24 06:21 UTC, tlt-java-courses commented on src/main/java/com/liadov/cat/lesson9/interfaces/Converter.java
> +    T convert(F from);
JavaDoc на публичный метод

2021-04-24 06:21 UTC, tlt-java-courses commented on src/main/java/com/liadov/cat/lesson9/ReflectionHandler.java
> + * ReflectionHandler
Не информатиыный JavaDoc

2021-04-24 06:21 UTC, tlt-java-courses commented on src/main/java/com/liadov/cat/lesson9/FileOperations.java
> + * FileOperations
Не информативный JavaDoc

2021-04-24 11:02 UTC, avlin87 commented on src/test/java/com/liadov/cat/lesson9/FileOperationsTest.java
> + * FileOperationsTest
добавил,
вау, с ликой, гораздо приличнее )

2021-04-24 11:03 UTC, avlin87 commented on src/test/java/com/liadov/cat/lesson9/ReflectionHandlerTest.java
> + * ReflectionHandlerTest
добавил
ReflectionHandlerTest test for {@link ReflectionHandler}

2021-04-24 11:04 UTC, avlin87 commented on src/test/java/com/liadov/cat/lesson9/ValueConverterTest.java
> + * ValueConverterTest
добавил
ValueConverterTest test for {@link ValueConverter}

2021-04-24 11:08 UTC, avlin87 commented on src/main/java/com/liadov/cat/lesson9/interfaces/Converter.java
> +    T convert(F from);
добавил
Method converting value from current Class type (F) to target class type (T)
@param from current Class of object
@return value converted to target Class

2021-04-24 11:13 UTC, avlin87 commented on src/main/java/com/liadov/cat/lesson9/ReflectionHandler.java
> + * ReflectionHandler
добавил 
ReflectionHandler - class populates fields that have @Value annotation
on objects of Classes that have @Entity annotation

2021-04-24 11:14 UTC, avlin87 commented on src/main/java/com/liadov/cat/lesson9/FileOperations.java
> + * FileOperations
добавил,
FileOperations - class extracts information from file.

2021-04-24 21:00 UTC, tlt-java-courses approved these changes

2021-04-24 21:00 UTC, tlt-java-courses approved these changes

2021-04-24 21:00 UTC, merged