create multi module structure
avlin87/epam-learn pull request #16
Opened 2021-05-03 20:27 UTC by avlin87

@tlt-java-courses ,
Проверьте, пожалуйста, домашнее задание по MAVEN

2021-05-09 06:20 UTC, tlt-java-courses approved these changes

2021-05-10 14:50 UTC, tlt-java-courses requested changes

2021-05-10 14:50 UTC, tlt-java-courses commented on pom.xml
>      <artifactId>liadov</artifactId>
Хорошо, если структура пакетов внутри проекта соответсвует groupId.artifactId сейчас же у тебя пакеты: `com.liadov.cat`. Давай приведём всё к одному виду.

2021-05-10 18:54 UTC, avlin87 commented on pom.xml
>      <artifactId>liadov</artifactId>
переименовал <groupId>com.liadov</groupId>
в <groupId>com.epam</groupId>

переименовал пакеты в 
com.epam.liadov

2021-05-10 19:12 UTC, tlt-java-courses approved these changes

2021-05-10 19:12 UTC, merged