implementation of task1 and task2
avlin87/epam-learn pull request #18
Opened 2021-05-22 03:18 UTC by avlin87

@tlt-java-courses 
Доброго дня, проверьте, пожалуйста,
ДЗ: Lesson 14

2021-05-22 13:36 UTC, tlt-java-courses requested changes
Тесты не проходят

2021-05-22 13:36 UTC, tlt-java-courses commented on liadov-db/src/main/resources/db/database_liadov_changelog.xml
> +    <include file="src/main/resources/db/changelog/customer_changelog-1.0.xml"/>
Зачем так много ченжлогов? Давай сделаем из них один

2021-05-22 13:36 UTC, tlt-java-courses commented on liadov-db/src/main/resources/db/changelog/customer_changelog-1.0.xml
> +        <loadData catalogName="CustomerData"
Это хорошо, что ты заиспользовал loadData, но обычно данные заливают, после первоначальной раскатки. 
Давай сделаем отдельный ченжлог с ченжсетами раскатки данных каждой таблицы

2021-05-22 13:36 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/CrudService.java
> +    public CrudService(EntityManagerFactory entityManagerFactory) {
Давай использовать ломбок

2021-05-22 13:36 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/CrudService.java
> +public class CrudService {
Давай сделаем 4 репозитория, которые будут уметь только CRUD. 
И данный сервис уже будет демонстративным.
Не будем всё под одну гребенку и воспользуемсяя преимуществами ООП

2021-05-22 13:36 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/entity/CrudEntity.java
> +public interface CrudEntity {
Решение хорошее, но давай не будем

2021-05-22 13:36 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/CrudService.java
> +    private <T> Optional<T> createEntityInDatabase(T crudEntity) {
хватит названия `create` и так понятно что работаем с entity и c базой данных
в остальных случаях аналогично

2021-05-22 13:36 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/entity/Customer.java
> +    @Column
Зачем нам пустые аннотации @Column?

2021-05-22 13:36 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/entity/Customer.java
> +@Table
Зачем нам пустые аннотации @Table?

2021-05-22 13:36 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/entity/Order.java
> +@Table(name = "[order]")
Почему таблица зовётся `[order]`?

2021-05-22 13:36 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/entity/Order.java
> +    public Order(String orderNumber, int customerId, Date orderDate, BigDecimal totalAmount) {
Для чего этот конструктор?

2021-05-22 13:36 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/entity/Order.java
> +    public Order() {
Давай использовать ломбок

2021-05-22 13:36 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/CrudService.java
> +            entityManager.close();
finally{} ??

2021-05-22 13:36 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/CrudService.java
> +            entityManager.close();
finally{} ??

2021-05-22 13:36 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/CrudService.java
> +        T entity = entityManager.find(entityClass, primaryKey);
Для чего ты сначала ищешь сущность, чтобы её после удалить? 
Если б ты писал SQL запрос на удаление, ты б тоже для начала SELECT делал?

2021-05-22 13:52 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/entity/Order.java
> +@Table(name = "[order]")
таблицу назвал [order] так как в противном случае система ищет её с большой буквы в базе данных при CRUD операциях и падает.
В базе имя без квадратных скобочек.

2021-05-22 19:34 UTC, avlin87 commented on liadov-db/src/main/resources/db/database_liadov_changelog.xml
> +    <include file="src/main/resources/db/changelog/customer_changelog-1.0.xml"/>
Сделал один
db_changelog-1.0.xml

2021-05-22 19:34 UTC, avlin87 commented on liadov-db/src/main/resources/db/changelog/customer_changelog-1.0.xml
> +        <loadData catalogName="CustomerData"
сделал 
loadData_changelog-1.0.xml

2021-05-22 19:41 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/entity/Customer.java
> +    @Column
убрал из всех POJO классов

2021-05-22 19:43 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/entity/Customer.java
> +@Table
убрал пустые аннотации @table
из POJO классов

2021-05-22 19:51 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/CrudService.java
> +            entityManager.close();
перенёс entityManager.close(); в finally блок

2021-05-22 19:52 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/CrudService.java
> +            entityManager.close();
перенёс entityManager.close(); в finally блок

2021-05-22 20:07 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/CrudService.java
> +    public CrudService(EntityManagerFactory entityManagerFactory) {
добавил @NonNull в конструктор

2021-05-22 20:17 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/entity/Order.java
> +    public Order(String orderNumber, int customerId, Date orderDate, BigDecimal totalAmount) {
конструктор использовался для создания заполененных сущностей перед отправкой в BD.
удалил.

2021-05-22 20:18 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/entity/Order.java
> +    public Order() {
конструктор удалил

2021-05-23 09:07 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/entity/CrudEntity.java
> +public interface CrudEntity {
CrudEntity удалил

2021-05-23 09:08 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/CrudService.java
> +public class CrudService {
создал отдельные репозитории в папке repository

2021-05-23 09:09 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/CrudService.java
> +    private <T> Optional<T> createEntityInDatabase(T crudEntity) {
поменя имена на 
save
update
find
delete

2021-05-23 09:10 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/CrudService.java
> +        T entity = entityManager.find(entityClass, primaryKey);
поправил

2021-05-23 20:08 UTC, tlt-java-courses approved these changes

2021-05-23 20:14 UTC, merged