implementation without stab
avlin87/epam-learn pull request #20
Opened 2021-06-01 23:50 UTC by avlin87

@tlt-java-courses 
Доброго дня, проверьте, пожалуйста

2021-06-03 18:57 UTC, tlt-java-courses requested changes
Не увидел тестов на сервисы

2021-06-03 18:57 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/config/ConfigurationDao.java
> +public class ConfigurationDao {
Как я говорил, принято называть классы конфигурации как ЧтоТоConfig
В твоём случае это DaoConfig. Но вообще я бы отрефакторил этот класс.

2021-06-03 18:57 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/config/ConfigurationDao.java
> +    public LocalContainerEntityManagerFactoryBean entityManagerFactory() {
Этот бин можно вынести в JpaConfig

2021-06-03 18:57 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/config/ConfigurationDao.java
> +    public DataSource dataSource() {
Этот бин в DataSourceConfig

2021-06-03 18:57 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/config/ConfigurationDao.java
> +    public JpaTransactionManager transactionManager(EntityManagerFactory entityManagerFactory) {
Этот бин в JpaConfig

2021-06-03 18:57 UTC, tlt-java-courses commented on pom.xml
> +                <artifactId>spring-webmvc</artifactId>
В рамках данного задания не должно быть spring web

2021-06-03 18:57 UTC, tlt-java-courses commented on pom.xml
> +                <artifactId>spring-web</artifactId>
В рамках данного задания не должно быть spring web

2021-06-03 18:57 UTC, tlt-java-courses commented on pom.xml
> +                <artifactId>spring-boot-starter-data-jpa</artifactId>
В рамках данного задания не должно быть spring data

2021-06-03 18:57 UTC, tlt-java-courses commented on pom.xml
> +                <artifactId>spring-orm</artifactId>
В рамках данного задания не должно быть spring data

2021-06-03 18:57 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/config/ConfigurationDao.java
> +    public PersistenceExceptionTranslationPostProcessor exceptionTranslation() {
Для чего бин?

2021-06-03 18:57 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/config/ConfigurationDao.java
> +    public Properties additionalProperties() {
Этот бин и оставшиеся в JpaConfig

2021-06-03 18:57 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/config/ConfigurationDaoStub.java
> +public class ConfigurationDaoStub {
С этим бином аналогично его не стаб версии, единственное... В стабе не должно быть бинов подключения к БД. При выполнении использования профиля вся работа приложения должна поддерживаться без подключения к БД. Сейчас же бины создаются, что некорректно

2021-06-03 18:57 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/entity/Customer.java
> +@Component
Зачем Entity помечать как бины? Это сущности а не бизнес логика

2021-06-03 18:57 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/repository/impl/CustomerRepositoryImpl.java
> +    private EntityManager entityManager;
Объясни как сейчас это работает. И какой компонент сюда придёт

2021-06-03 18:57 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/repository/impl/CustomerRepositoryImpl.java
> +@Repository
В рамках задания нет репозиториев у нас. Мы Spring Data не используем

2021-06-03 18:57 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/repository/stub/CustomerRepositoryStub.java
> +    private EntityFactory factory;
Давай автоварийть через конструктор с использованием ломбока

2021-06-03 18:57 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/repository/impl/CustomerRepositoryImpl.java
> +    public boolean save(Customer customer) {
Что true\false? Репозитории объекты возвращать должны, которые нашли/сохранили. true/false Только в методе delete подойдет

2021-06-03 18:57 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/service/impl/CustomerServiceImpl.java
> +    public CustomerServiceImpl(CustomerRepository customerRepository) {
Давай использовать ломбок

2021-06-03 18:57 UTC, tlt-java-courses commented on pom.xml
> +                <artifactId>spring-web</artifactId>
Хотя я так понимаю используется чтобы с томкатом подружить?

2021-06-03 19:58 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/entity/Customer.java
> +@Component
поправил

2021-06-03 20:30 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/repository/impl/CustomerRepositoryImpl.java
> +@Repository
поправил на @Component

2021-06-03 20:41 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/repository/stub/CustomerRepositoryStub.java
> +    private EntityFactory factory;
попраил,
воспользовался @RequiredArgsConstructor
сделал переменные для автоваринга final

2021-06-03 20:43 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/service/impl/CustomerServiceImpl.java
> +    public CustomerServiceImpl(CustomerRepository customerRepository) {
попраил,
воспользовался @RequiredArgsConstructor

2021-06-03 20:54 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/config/ConfigurationDao.java
> +    public PersistenceExceptionTranslationPostProcessor exceptionTranslation() {
я думал, что он транслирует эксепшен базы данных в "понятный",
но удалив не вижу разницы...
должен был работать с моим LocalContainerEntityManagerFactoryBean и @Repository
возможно нужно использовать с spring data.

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/dao/annotation/PersistenceExceptionTranslationPostProcessor.html

2021-06-03 20:54 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/config/ConfigurationDao.java
> +    public Properties additionalProperties() {
переместил

2021-06-03 20:55 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/config/ConfigurationDao.java
> +    public LocalContainerEntityManagerFactoryBean entityManagerFactory() {
переместил

2021-06-03 20:55 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/config/ConfigurationDao.java
> +    public DataSource dataSource() {
переместил

2021-06-03 20:55 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/config/ConfigurationDao.java
> +    public JpaTransactionManager transactionManager(EntityManagerFactory entityManagerFactory) {
переместил

2021-06-03 20:56 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/config/ConfigurationDao.java
> +public class ConfigurationDao {
Переименовал

2021-06-04 08:25 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/config/ConfigurationDaoStub.java
> +public class ConfigurationDaoStub {
да, по ошибке оставил содержимое,
переделал.

2021-06-04 08:35 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/repository/impl/CustomerRepositoryImpl.java
> +    private EntityManager entityManager;
через аннотацию @PersistenceContext
сюда приходит EntityManager создаваемый контейниром из LocalContainerEntityManagerFactoryBean.

мне понравилось это в лекции 14-го урока Lection 14 - JPA.pptx:
![image](https://user-images.githubusercontent.com/33938644/120772014-e40b9b00-c530-11eb-8360-c6ff651df188.png)

очень хотел сюда его прикрутить...
так понимаю, что удалив spring-orm, spring-boot-starter-data-jpa, эта реализация работать прекратит...

2021-06-04 08:40 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/service/impl/CustomerServiceImpl.java
> +    public CustomerServiceImpl(CustomerRepository customerRepository) {
не получается исправить для Servlet
при автоваеренге с конструктором - падает мой метод init
через который получаеся springContext

2021-06-04 09:09 UTC, avlin87 commented on pom.xml
> +                <artifactId>spring-web</artifactId>
да, используется, чтобы работал томкад

2021-06-04 09:09 UTC, avlin87 commented on pom.xml
> +                <artifactId>spring-web</artifactId>
т.е. можно оставить?

2021-06-04 09:11 UTC, avlin87 commented on pom.xml
> +                <artifactId>spring-webmvc</artifactId>
spring-webmvc удалил

2021-06-04 09:44 UTC, avlin87 commented on pom.xml
> +                <artifactId>spring-boot-starter-data-jpa</artifactId>
удалил

2021-06-04 09:44 UTC, avlin87 commented on pom.xml
> +                <artifactId>spring-orm</artifactId>
удалил...

2021-06-04 15:16 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/repository/impl/CustomerRepositoryImpl.java
> +    public boolean save(Customer customer) {
Исправил

2021-06-04 17:10 UTC, avlin87 commented
"Не увидел тестов на сервисы"
добавил

2021-06-05 07:39 UTC, tlt-java-courses requested changes

2021-06-05 07:39 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/config/DaoStubConfig.java
> +    public MessageSource messageSource() {
А локаль и messageSourse относится к Dao?

2021-06-05 07:39 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/entity/Order.java
> +import org.springframework.stereotype.Component;
Лишний импорт

2021-06-05 07:39 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/entity/Product.java
> +import org.springframework.stereotype.Component;
Лишний импорт

2021-06-05 07:39 UTC, tlt-java-courses commented on liadov-db/src/main/resources/db/changelog/db_changelog-1.0.xml
> +                <constraints nullable="false" primaryKey="false" unique="false"/>
Не обратил внимание ранее. Т.к. ты уже сдавал это задание раньше и условно его уже раскатили в рабочей среде, то правка уже существующих скриптов не позволительна, т.к. придётся сносить базу. Для последующих обновлений БД необхоимо писать новый миграционный скрипт с апдейтами

2021-06-05 07:39 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/repository/impl/CustomerRepositoryImpl.java
> +            return Optional.ofNullable(customer);
Уже лучше. Но здесь вопрос, будет ли обновленная сущность? Т.е. если я создаю новую сущность без id, которое должно само сгенерироваться, вернется ли обновленная сущность мне из метода?

2021-06-05 07:39 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/CrudServiceMain.java
> +        CustomerRepository customerRepository = context.getBean(CustomerRepository.class);
Я не против демонстрации репозиториев, но мне всё же интересна работа сервисов.

2021-06-05 07:39 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/CrudServiceMain.java
> +    private static void demonstrateCustomerOperations(ApplicationContext context) {
При запуске часто падают такие ошибки: 
![image](https://user-images.githubusercontent.com/75726498/120884000-8ab77080-c5f1-11eb-9ed6-a7138afafb81.png)
![image](https://user-images.githubusercontent.com/75726498/120884003-8f7c2480-c5f1-11eb-8ae0-d57e46acfc50.png)
![image](https://user-images.githubusercontent.com/75726498/120884006-960a9c00-c5f1-11eb-999c-f7a43f25504d.png)

2021-06-05 07:39 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/repository/impl/OrderProductRepositoryImpl.java
> +public class OrderProductRepositoryImpl implements OrderProductRepository {
Этого репозитория просто не должно быть. У тебя же 4 сущности, следовательно и 4 репозитория, по одному на каждую. А сохранение связей many-to-many должно происходит посредством правильно настроенной JPA аннотациями.

2021-06-05 07:39 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/service/CustomerService.java
> +    boolean save(Customer customer);
Лучше чтобы сервис тоже возвращал какой-то результат. Ты в дальнейшем для оперирования сущностями будешь работать только через сервисы, наверное тебе будет необходимо иметь какой-то результат на руках.

2021-06-05 07:39 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/service/CustomerService.java
> +    boolean save(Customer customer);
С update тоже самое.

2021-06-05 07:39 UTC, tlt-java-courses commented on pom.xml
> +                <artifactId>spring-web</artifactId>
Ок можно

2021-06-05 08:06 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/entity/Order.java
> +import org.springframework.stereotype.Component;
удалил

2021-06-05 08:07 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/entity/Product.java
> +import org.springframework.stereotype.Component;
удалил импорт

2021-06-05 12:49 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/config/DaoStubConfig.java
> +    public MessageSource messageSource() {
переименовал класс в StubConfig

2021-06-05 14:37 UTC, avlin87 commented on liadov-db/src/main/resources/db/changelog/db_changelog-1.0.xml
> +                <constraints nullable="false" primaryKey="false" unique="false"/>
откатил db_changelog-1.0.xml до состояния 14-й лекции,
добавил db_changelog-1.1.xml для изменения таблиц

2021-06-05 14:50 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/repository/impl/CustomerRepositoryImpl.java
> +            return Optional.ofNullable(customer);
Возвращается обновлённая сущность.
метод работает с присланным customer.
![image](https://user-images.githubusercontent.com/33938644/120895493-31216700-c62e-11eb-8b37-2d518f387741.png)
Может я вопрос не понял...

2021-06-05 14:53 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/CrudServiceMain.java
> +    private static void demonstrateCustomerOperations(ApplicationContext context) {
я предполагал демонстрацию работы "профиля local ru RU или en US"
переделаю, чтобы работало с базой.

2021-06-05 20:11 UTC, merged

2021-06-05 20:25 UTC, tlt-java-courses commented
1. Ошибка при апдейте ликвибейз скриптов
![image](https://user-images.githubusercontent.com/75726498/120904290-88d6c700-c65c-11eb-8c4a-5128df3216da.png)
2. Ошибки при работе приложения с Persistance слоем
![image](https://user-images.githubusercontent.com/75726498/120904307-9e4bf100-c65c-11eb-9756-ac7b54156b47.png)
3. Сущностей 4, а репозиториев 5 - некорректно настроенный JPA 
![image](https://user-images.githubusercontent.com/75726498/120904411-3ea21580-c65d-11eb-9e33-3d3bb15d3af2.png)
4. Класс для генерации тестовых данных в основном пакете
![image](https://user-images.githubusercontent.com/75726498/120904507-b3754f80-c65d-11eb-8140-458d44c00756.png)
4. Не соблюдение клин кода 
  1. Наименование классов вводят в заблужение
![image](https://user-images.githubusercontent.com/75726498/120904334-c4719100-c65c-11eb-8a5e-79a89fe48115.png)
  2. Наименования переменных
![image](https://user-images.githubusercontent.com/75726498/120904436-5f6a6b00-c65d-11eb-9b2a-6f34774e82b6.png)

Gson можно было сделать бином.

2021-06-05 20:48 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/CrudServiceMain.java
> +        CustomerRepository customerRepository = context.getBean(CustomerRepository.class);
Исправил на демонстрацию Service

2021-06-05 20:49 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/CrudServiceMain.java
> +    private static void demonstrateCustomerOperations(ApplicationContext context) {
поправил

2021-06-05 20:49 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/repository/impl/OrderProductRepositoryImpl.java
> +public class OrderProductRepositoryImpl implements OrderProductRepository {
Удалил

2021-06-05 20:49 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/service/CustomerService.java
> +    boolean save(Customer customer);
Поправил