HomeWork implemented 17
avlin87/epam-learn pull request #21
Opened 2021-06-10 23:24 UTC by avlin87

@tlt-java-courses 
Проверьте, пожалуйста, задание 17

2021-06-11 18:37 UTC, tlt-java-courses requested changes
**0. Давай исправим все замечания что я оставлял к 16 ПР**
1. Я исполнил запрос _http://localhost:8080/customer?id=1_ в БД сущности c id нет, а вернулся ответ 
```json
{
    "customerId": 0,
    "customerName": null,
    "phone": null
}
```
Проверь все свои запросы что они корректно отрабатывают.

2. Для чего куча jar-ников в api модуле? 
Необходимо просто сказать мавену собирать всё в один исполняемый war.
3. ликвибейз скрипты всё ещё не раскатываются

2021-06-11 18:37 UTC, tlt-java-courses commented on liadov-api/src/main/java/com/epam/liadov/dto/OrderDto.java
> +    private int orderID;
А если тебе фронт не пришлёт id, то какое значение в системе будет?

2021-06-11 18:37 UTC, tlt-java-courses commented on liadov-api/src/main/java/com/epam/liadov/resource/CustomerResource.java
> +public interface CustomerResource<T> {
Дженерик хорошо, но зачем?

2021-06-11 18:37 UTC, tlt-java-courses commented on liadov-api/src/main/java/com/epam/liadov/resource/CustomerResource.java
> +    T getCustomer(@RequestParam Integer id);
Давай для таких запросов с id использовать PathVariable

2021-06-11 18:37 UTC, tlt-java-courses commented on liadov-impl/pom.xml
> +            <version>1.0-SNAPSHOT</version>
Почему версия задана в дочернем модуле а не родительском?

2021-06-11 18:37 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/config/JpaConfig.java
> +    public LocalContainerEntityManagerFactoryBean entityManagerFactory() {
Зачем конфигурация entityManager? Мы используем SpringData

2021-06-11 18:37 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/config/JpaConfig.java
> +    public JpaTransactionManager transactionManager(EntityManagerFactory entityManagerFactory) {
Зачем конфигурация transactionManager? Мы используем SpringData

2021-06-11 18:37 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/domain/Customer.java
> +package com.epam.liadov.domain;
Тогда уж domain.entity

2021-06-11 18:37 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/domain/factory/EntityFactory.java
>  public class EntityFactory {
Зачем этот класс нужен?

2021-06-11 18:37 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/repository/CustomerRepository.java
> +    <S extends Customer> S save(S customer);
Для чего здесь все эти методы если они есть в Crud репозитории?

2021-06-11 18:37 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/repository/CustomerRepository.java
> +public interface CustomerRepository extends CrudRepository<Customer, Integer> {
Мы используем Jpa... Давай использовать JpaRepository

2021-06-11 18:37 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/resource/impl/CustomerResourceImpl.java
> +    public Customer addCustomer(Customer customer) {
Клиет не должен знать как выглядят внутренние сущности системы. Используй ДТО

2021-06-11 18:37 UTC, tlt-java-courses commented on liadov-impl/src/main/java/com/epam/liadov/service/CustomerService.java
> +    boolean delete(int primaryKey);
primaryKey ?

2021-06-11 18:37 UTC, tlt-java-courses commented on pom.xml
> +                <scope>compile</scope>
Почему скойп compile?

2021-06-11 18:37 UTC, tlt-java-courses commented on pom.xml
> +                        <exclude>**/config/**</exclude>
доменные сущности тоже можно заэкслюдить

2021-06-12 09:24 UTC, avlin87 commented on liadov-impl/pom.xml
> +            <version>1.0-SNAPSHOT</version>
перенёс версию в родительский модуль.

2021-06-12 09:40 UTC, avlin87 commented on pom.xml
> +                        <exclude>**/config/**</exclude>
добавил в исключения.

2021-06-12 09:43 UTC, avlin87 commented on pom.xml
> +                <scope>compile</scope>
Убрал <scope>compile</scope> так как и так он используюется по дефолту

2021-06-12 09:46 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/domain/factory/EntityFactory.java
>  public class EntityFactory {
для генерации Кастомера, Ордера, Продукта, Сапплаера с рандомными данными,
использовался в прошлой домашней работе для демонстрации работы приложения
и
для генерирования тестовых данных в тестах

2021-06-12 09:46 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/domain/Customer.java
> +package com.epam.liadov.domain;
поправил

2021-06-12 09:52 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/repository/CustomerRepository.java
> +    <S extends Customer> S save(S customer);
понял, спасибо )
почистил, оставил только List<Order> findAllByCustomerId(Integer customerId); из OrderRepository

2021-06-12 09:53 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/repository/CustomerRepository.java
> +public interface CustomerRepository extends CrudRepository<Customer, Integer> {
Поправил

2021-06-12 10:01 UTC, avlin87 commented on liadov-api/src/main/java/com/epam/liadov/dto/OrderDto.java
> +    private int orderID;
Получается, так как у меня int тип - то значение переменной никогда и не было null
при испоавлении на Integer при создании сущности придётся в рест отправлять что-то, хотя у меня сейчас ID автогенерится.
Так что убрал @NotNull.

2021-06-12 10:48 UTC, avlin87 commented on liadov-api/src/main/java/com/epam/liadov/resource/CustomerResource.java
> +    T getCustomer(@RequestParam Integer id);
Исправил на PathVariable - поправил коллекцию постман

2021-06-12 11:19 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/service/CustomerService.java
> +    boolean delete(int primaryKey);
поменял primaryKey на 
customerId
productId
orderId
supplierId
соответственно.

2021-06-12 12:44 UTC, avlin87 commented
> **0. Давай исправим все замечания что я оставлял к 16 ПР**
> 
> 1. Я исполнил запрос _http://localhost:8080/customer?id=1_ в БД сущности c id нет, а вернулся ответ
> 
> ```json
> {
>     "customerId": 0,
>     "customerName": null,
>     "phone": null
> }
> ```
> 
> Проверь все свои запросы что они корректно отрабатывают.
> 
> 1. Для чего куча jar-ников в api модуле?
>    Необходимо просто сказать мавену собирать всё в один исполняемый war.

0. 16 ПР - я исправлял. С исправленого приступил к ДЗ №17
перепроверил, сейчас не вижу, чтобы что-то из замечаний осталось не исправленым.

1. в БД сущности c id нет 
исправил - в случае отсутсвия сущности возвращаю 204 - HttpStatus.NO_CONTENT

2. куча jar-ников в api модуле
они не нужны - образовались во время экспериментов с упаковкой.
сейчас упаковывается в war в impl модуле

2021-06-12 13:49 UTC, avlin87 commented on liadov-api/src/main/java/com/epam/liadov/resource/CustomerResource.java
> +public interface CustomerResource<T> {
DTO не будет отличатся от Entity класса и предположил, что в таком случае нет необходимости в DTO

исправил - перевёл на DTO

2021-06-12 13:49 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/resource/impl/CustomerResourceImpl.java
> +    public Customer addCustomer(Customer customer) {
Перевёл Customer и Supplier на Dto
Order и Product уже на Dto

2021-06-12 13:52 UTC, avlin87 commented on liadov-impl/src/main/java/com/epam/liadov/config/JpaConfig.java
> +    public JpaTransactionManager transactionManager(EntityManagerFactory entityManagerFactory) {
предположительно это удалённый комментарий.
Пока пытался обойтись без transactionManager внёс правки
удалил класс для датасурса - вернулся к persistence.xml

2021-06-12 19:53 UTC, avlin87 commented
0. Давай исправим все замечания что я оставлял к 16 ПР

на всякий случай переименовал StubConfig в MessageSourceConfig

2021-06-12 21:06 UTC, merged